# Generated by Django 5.2.17 on 2026-09-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='adzuna', max_length=50)),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('job_url', models.URLField(max_length=500)),
                ('employment_type', models.CharField(blank=True, max_length=80)),
                ('experience_level', models.CharField(blank=True, max_length=80)),
                ('salary_min', models.BigIntegerField(blank=True, null=True)),
                ('salary_max', models.BigIntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(default='Adzuna', max_length=80)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at', '-posted_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='jobs_unique_provider_external_id')],
            },
        ),
    ]
