# Generated by Django 5.2.17 on 2026-09-28 15:22

import django.db.models.deletion
import resumes.models
import resumes.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=resumes.models.resume_upload_to, validators=[resumes.validators.validate_resume_file])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX')], max_length=4)),
                ('file_size', models.PositiveBigIntegerField()),
                ('extracted_text', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
