# Generated by Django 5.2.17 on 2026-09-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resumeanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='target_roles',
            field=models.JSONField(default=list),
        ),
    ]
